### ISSUE TITLE
Problem setting low range to value other than 0

### ISSUE THREAD

**Issue by bsorbom** [zach-hartwig/ADAQAnalysis#1] opened 2015-05-16 17:39 UTC
If I try to plot a histogram with a minimum pulse unit range greater than 0 by using the "minimum" input bin under the "spectra" tab, the first bin gets an enormous number of counts. Does this have something to do with the "underflow" bin that we had issues with while storing the NaI array data?

**Comment by zach-hartwig** [comment] 2015-05-16 18:58
Thanks for reporting this issue. In short, no, the issue is not related to ROOT TH1 underflow bins but is related to how the X axis limits of the TH1 showing the spectrum are set using a combination of the spectrum min/max bin and the position of the horizontal double slider under the canvas. When the slider lower limit is at zero position, this sets the XAxis range to "0" and trigger display of the underflow bin.

I've pushed a fix to the HEAD of the master branch that correctly sets spectrum TH1F X-axis ranges for arbitrary bin min/max limits and prevents showing the under/overflow bins. Tests show it works well for spectra, background calculation/subtraction, integration, and fitting. Please let me know if this fix gives the correct behavior.

**Comment by bsorbom** [comment] 2015-05-16 20:13
Yes, the new version gives the correct behavior. Thanks!

**Comment by zach-hartwig** [comment] 2015-05-16 20:14
Excellent. Closing this issue.

**Closed as completed by zach-hartwig** 2015-05-16 20:14 UTC
